name: Create docker images

on: [push]

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db-type: [postgresql, mysql]

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    -
      name: Checkout
      uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}


    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        tags:  wojiuchigua/umami/${{ matrix.db-type }}-${{ env.RELEASE_VERSION }}, wojiuchigua/umami/${{ matrix.db-type }}-latest
        build-args: DATABASE_TYPE=${{ matrix.db-type }}

